export const options = [
  { value: '종이/종이팩' },
  { value: '고철' },
  { value: '금속캔' },
  { value: '비닐' },
  { value: '플라스틱' },
  { value: '스티로폼' },
  { value: '불연성종량제' },
  { value: '일반쓰레기' },
];

export const items = [
  { value: '빨대', color: 'red' },
  { value: '수건', color: 'volcano' },
  { value: '전단지', color: 'orange' },
  { value: '뽁뽁이', color: 'gold' },
  { value: '나무 도마', color: 'magenta' },
  { value: '호일', color: 'lime' },
  { value: '보온병', color: 'green' },
  { value: '유리', color: 'cyan' },
  { value: '장난감', color: 'blue' },
  { value: '알약 포장재', color: 'geekblue' },
  { value: '컵라면 용기', color: 'purple' },
  { value: '일회용 봉투', color: 'red' },
  { value: '아이스팩', color: 'orange' },
  { value: '약', color: 'magenta' },
  { value: '핸드 타월', color: 'gold' },
  { value: '영수증', color: 'lime' },
  { value: '고지서', color: 'green' },
  { value: '종이 조각', color: 'cyan' },
  { value: '스프링 공책', color: 'blue' },
  { value: '종이컵', color: 'geekblue' },
];
